/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ch.hsr.univote.unigen.gui;

/**
 *
 * @author Gian
 */
public class FailureConfiguration extends javax.swing.JPanel {

    /**
     * Creates new form test
     */
    public FailureConfiguration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);

        jLabel3.setText("Schnorr Parameters");
        add(jLabel3);
        add(jSeparator1);

        jCheckBox6.setSelected(true);
        jCheckBox6.setText("Schnorr's P is prime");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        add(jCheckBox6);

        jCheckBox8.setSelected(true);
        jCheckBox8.setText("Schnorr's G is generator");
        add(jCheckBox8);

        jCheckBox7.setSelected(true);
        jCheckBox7.setText("Schnorr's Q is prime");
        add(jCheckBox7);

        jCheckBox9.setSelected(true);
        jCheckBox9.setText("Schnorr's P is SafePrime");
        add(jCheckBox9);
        add(jSeparator2);
        add(jSeparator3);

        jLabel2.setText("ElGamal Parameters");
        add(jLabel2);
        add(jSeparator4);

        jCheckBox5.setSelected(true);
        jCheckBox5.setText("ElGamal P is prime");
        add(jCheckBox5);

        jCheckBox10.setSelected(true);
        jCheckBox10.setText("ElGamal Q is prime");
        add(jCheckBox10);

        jCheckBox11.setSelected(true);
        jCheckBox11.setText("ElGamal G is prime");
        add(jCheckBox11);

        jCheckBox12.setSelected(true);
        jCheckBox12.setText("ElGamal P is SafePrime");
        add(jCheckBox12);

        jCheckBox13.setSelected(true);
        jCheckBox13.setText("ElGamal Parameter Length");
        add(jCheckBox13);
        add(jSeparator5);
        add(jSeparator6);

        jLabel1.setText("Certificates");
        add(jLabel1);
        add(jSeparator7);

        jCheckBox14.setSelected(true);
        jCheckBox14.setText("CA Certificate");
        add(jCheckBox14);

        jCheckBox15.setSelected(true);
        jCheckBox15.setText("EM Certificate");
        add(jCheckBox15);

        jCheckBox16.setSelected(true);
        jCheckBox16.setText("EA Certificate");
        add(jCheckBox16);

        jCheckBox17.setSelected(true);
        jCheckBox17.setText("Tallier Certificate -> WELCHER?");
        add(jCheckBox17);

        jCheckBox18.setSelected(true);
        jCheckBox18.setText("Mixer Certificate -> WELCHER?");
        add(jCheckBox18);

        jCheckBox19.setSelected(true);
        jCheckBox19.setText("Voters Certificates -> WIEVIELE?");
        add(jCheckBox19);
        add(jSeparator9);
        add(jSeparator8);

        jLabel4.setText("Signatures");
        add(jLabel4);
        add(jSeparator10);

        jCheckBox23.setSelected(true);
        jCheckBox23.setText("ElGamal Parameter Signature");
        add(jCheckBox23);

        jCheckBox22.setSelected(true);
        jCheckBox22.setText("Tallier Mixer Certificate Signature");
        add(jCheckBox22);

        jCheckBox20.setSelected(true);
        jCheckBox20.setText("EA Certificate Signature");
        add(jCheckBox20);

        jCheckBox25.setSelected(true);
        jCheckBox25.setText("Encryption Keys Signature");
        add(jCheckBox25);

        jCheckBox24.setSelected(true);
        jCheckBox24.setText("Tallier NIZKP Signature");
        add(jCheckBox24);

        jCheckBox21.setSelected(true);
        jCheckBox21.setText("Election Basic Parameters Signature");
        add(jCheckBox21);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
